### ISSUE TITLE
NDEFReader Fails. Unknown card type

### ISSUE THREAD

**Issue by samsamm777** [grundid/nfctools-examples#3]
java -cp nfctools-examples.jar org.nfctools.examples.ndefreader.NdefReaderDemo

`root@ubuntu001:/home/administrator/Downloads# java -cp nfctools-examples-ultralight.jar org.nfctools.examples.ndefreader.NdefReaderDemo^[[B^[[A^[[AINFO : org.nfctools.examples.ndefreader.NdefReaderDemo - Listening...
DEBUG: org.nfctools.spi.acs.Acr122ReaderWriter - Starting new thread Thread-0
INFO : org.nfctools.examples.ndefreader.NdefReaderDemo - Done
Exception in thread "Thread-0" java.lang.RuntimeException: org.nfctools.mf.MfException: unknown card type: 804F0CA00000030603000300000000
    at org.nfctools.spi.acs.PollingCardScanner.run(PollingCardScanner.java:51)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.nfctools.mf.MfException: unknown card type: 804F0CA00000030603000300000000
    at org.nfctools.spi.acs.CardResolver.resolvecard(CardResolver.java:44)
    at org.nfctools.spi.acs.PollingCardScanner.waitForCard(PollingCardScanner.java:60)
    at org.nfctools.spi.acs.PollingCardScanner.run(PollingCardScanner.java:45)
    ... 1 more`

Any ideas?

**Comment by honeynatividad** [comment]
Have you ever resolve this issue? Because Im also getting this error. but when I tried the scancard, its working. Do i need to configure soemthing?

**Comment by riverajefer** [comment]
is there any solution to the problem?

**Comment by Premier** [comment]
Same error, i'm using Ultralight Type 2 NFC

**Comment by grundid** [comment]
I'm sorry, but I do not have access to ultralight type 2 cards right now. 
I assume this is an ID issue. You would have to change to possible IDs in der CardResolver class and then try this again.
